name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thank you so much for raising the issue! I will have a look at it soon. Cheers'
        pr-message: 'Thanks for the pull request. I will have a look at it soon. Have a nice day!'
